# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XSNDU7iZQD5rMI2ZLDBK-I0wJT7HWNaN
"""

import pandas as pd
import numpy as np
import argparse

def extract_data(source):
    return pd.read_csv(source)


def transform_data(data):
    new_data = data.copy()
    
    new_data['Age'].fillna(value=new_data['Age'].mean(), inplace = True)

    new_data.drop(['Cabin','Name','Ticket'],axis=1,inplace=True)

    IQR_Age=new_data['Age'].quantile(0.75)-new_data['Age'].quantile(0.25)
  
    Upper_OutlierLimit2=new_data['Age'].quantile(0.75)+1.5*IQR_Age

    new_data['Age']=np.where(new_data['Age']>Upper_OutlierLimit2,new_data['Age'].quantile(0.95),new_data['Age'])
    return new_data

def load_data(data,target):
    data.to_csv(target)

if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('source',help='source csv')
    parser.add_argument('target', help='target csv')
    args = parser.parse_args()

    print("Staring....")
    df=extract_data(args.source)
    new_df = transform_data(df)
    load_data(new_df,args.target)
    print("complete!!")